### PR TITLE
Restore behaviour concerning endstops

### PR DESCRIPTION
**Pull request by Banjer**
Some configuration changes to restore some of the behaviour Nopheads original firmware had concerning homing and preventing endstops from getting hit on moves other then homing.

### CODE REVIEW

**Comment by neildarlow** [comment]
We have:
#define ENDSTOPS_ONLY_FOR_HOMING // If defined the endstops will only be used for homing

At other times the head will not be moved beyond -100 to +100 for X,Y and 0 to 200 for Z. What is the problem with this?

**Comment by Banjer** [comment]
I have been a bit busy the last few days, and didn't have time to reply, but the current configuration doesn't seem to offset the hame positions (enough). I'll dive a bit deeper in this weekend and come back with a more extensive reply.

**Comment by neildarlow** [comment]
OK, taken a look at this.

With my -100, -100 setting and a centred rectangular print we appear to be 1.5mm and 1.0mm out on X and Y. We should probably use -101.5 and -101.0 for X and Y Home respectively.

I would prefer to fix this for both manually set and calculated home positions (I have a feeling that calculated will become the fashion in the future). <del>Z-wise, I am not sure that Z Height - 0.1mm is the right thing to do. Maybe 201.0mm (1mm outside the build area) would be a better value.</del>

It would be great if you can confirm my 1.5mm and 1.0mm offset values are correct.

**Comment by neildarlow** [comment]
I have re-instated the X and Y Home offsets but presently left Z alone.

**Comment by Banjer** [comment]
Niel, still haven't got the time to have a closer look, but your solution seems to be better, and everything works nicely now, thanks.

**Pull request closed without merging**
